version: '3.7'
services:
  web:
    container_name: flask_mongodb_docker_tutorial
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mongo:latest
    container_name: mymongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

